# Generated by Django 4.2.2 on 2023-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='telegram',
        ),
        migrations.AddField(
            model_name='signal',
            name='binance_api_hash',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='binance_api_key',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='binance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signal',
            name='channel_invite_link',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='message_format',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='message_prefix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='message_suffix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='parse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signal',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TelegramAlert',
        ),
    ]
