# Generated by Django 4.2.2 on 2023-11-28 21:21

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0002_remove_signal_telegram_signal_binance_api_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='binance_enabled',
            new_name='mt5_enabled',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='binance_api_hash',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='binance_api_key',
        ),
        migrations.AddField(
            model_name='signal',
            name='mt5_login',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30, null=True)),
        ),
        migrations.AddField(
            model_name='signal',
            name='mt5_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=60, null=True)),
        ),
        migrations.AddField(
            model_name='signal',
            name='mt5_server',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30, null=True)),
        ),
    ]
