# Generated by Django 4.2.2 on 2023-11-30 15:13

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0004_remove_signal_channel_invite_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='channel_chat_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='message_format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='message_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='message_suffix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='mt5_login',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30, null=True)),
        ),
        migrations.AlterField(
            model_name='signal',
            name='mt5_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=60, null=True)),
        ),
        migrations.AlterField(
            model_name='signal',
            name='mt5_server',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30, null=True)),
        ),
    ]
