# Generated by Django 4.2.2 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0005_alter_signal_channel_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='mt5_lot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
