# Generated by Django 4.2.2 on 2023-12-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signal_api', '0008_alter_discord_link_id_alter_mt5_link_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord_Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parse', models.BooleanField(default=False)),
                ('channel_chat_id', models.CharField(blank=True, max_length=15, null=True)),
                ('message_format', models.CharField(blank=True, max_length=500, null=True)),
                ('message_prefix', models.CharField(blank=True, max_length=200, null=True)),
                ('message_suffix', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT5_Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('meta_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parse', models.BooleanField(default=False)),
                ('limit', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('plan', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('entry', models.FloatField()),
                ('sl', models.FloatField()),
                ('side', models.CharField(max_length=5)),
                ('quantity', models.FloatField()),
                ('mt5_webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.mt5_webhook')),
            ],
        ),
        migrations.CreateModel(
            name='TakeProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_Webhook',
            fields=[
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parse', models.BooleanField(default=False)),
                ('hits', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('plan', models.CharField(max_length=5)),
                ('message_format', models.CharField(blank=True, max_length=500, null=True)),
                ('message_prefix', models.CharField(blank=True, max_length=200, null=True)),
                ('message_suffix', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.telegram_webhook')),
            ],
        ),
        migrations.RemoveField(
            model_name='mt5_link',
            name='webhook',
        ),
        migrations.RemoveField(
            model_name='signalwebhook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegram_link',
            name='webhook',
        ),
        migrations.DeleteModel(
            name='Discord_Link',
        ),
        migrations.DeleteModel(
            name='MT5_Link',
        ),
        migrations.DeleteModel(
            name='SignalWebhook',
        ),
        migrations.DeleteModel(
            name='Telegram_Link',
        ),
    ]
