# Generated by Django 4.2.2 on 2023-12-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0009_discord_webhook_mt5_webhook_order_takeprofit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mt5',
        ),
    ]
