# Generated by Django 4.2.2 on 2023-12-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signal_api', '0010_remove_order_mt5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5_webhook',
            old_name='id',
            new_name='webhook_id',
        ),
        migrations.RemoveField(
            model_name='discord_webhook',
            name='channel_chat_id',
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='plan',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='mt5_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='takeprofit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DiscordChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_webhook_url', models.CharField(max_length=20)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.telegram_webhook')),
            ],
        ),
    ]
