# Generated by Django 4.2.2 on 2023-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0011_rename_id_mt5_webhook_webhook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchat',
            name='channel_webhook_url',
            field=models.CharField(max_length=200),
        ),
    ]
