# Generated by Django 4.2.2 on 2023-12-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0012_alter_discordchat_channel_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchat',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.discord_webhook'),
        ),
    ]
