# Generated by Django 4.2.2 on 2023-12-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0014_order_date_created_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discord_webhook',
            old_name='limit',
            new_name='chat_limit',
        ),
        migrations.RenameField(
            model_name='telegram_webhook',
            old_name='id',
            new_name='webhook_id',
        ),
        migrations.RemoveField(
            model_name='discord_webhook',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='mt5_webhook',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='mt5_webhook',
            name='parse',
        ),
        migrations.RemoveField(
            model_name='mt5_webhook',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='telegram_webhook',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='telegram_webhook',
            name='plan',
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='hit_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='subscription_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discord_webhook',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='hit_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='chat_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='hit_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='status',
            field=models.CharField(default='active', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discord_webhook',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mt5_webhook',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegram_webhook',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
