# Generated by Django 4.2.2 on 2023-12-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0015_rename_limit_discord_webhook_chat_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='magic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='q_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='td',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trailing_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CloseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('magic', models.IntegerField(blank=True, null=True)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('mt5_webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.mt5_webhook')),
            ],
        ),
    ]
