# Generated by Django 4.2.2 on 2024-01-17 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signal_api', '0016_order_magic_order_q_type_order_td_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='_all',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='ModifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('magic', models.IntegerField(blank=True, null=True)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('mt5_webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_api.mt5_webhook')),
            ],
        ),
    ]
