# Generated by Django 4.2.2 on 2024-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0017_alert_content_alert_user_closeorder__all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binance_Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
