# Generated by Django 4.2.2 on 2024-01-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0018_binance_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='webhook_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
