# Generated by Django 4.2.2 on 2024-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0019_alert_webhook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
