# Generated by Django 4.2.2 on 2024-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0022_alter_alert_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['content_type', 'object_id'], name='signal_api__content_154490_idx'),
        ),
    ]
