# Generated by Django 4.2.2 on 2024-01-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0023_alert_signal_api__content_154490_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='content',
            new_name='text',
        ),
    ]
