# Generated by Django 4.2.2 on 2024-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0024_rename_content_alert_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
