# Generated by Django 4.2.2 on 2024-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0026_alert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_webhook',
            name='identifier',
            field=models.CharField(default='disc', max_length=10),
        ),
        migrations.AddField(
            model_name='mt5_webhook',
            name='identifier',
            field=models.CharField(default='mt5', max_length=10),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='identifier',
            field=models.CharField(default='tg', max_length=10),
        ),
    ]
