# Generated by Django 4.2.2 on 2024-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0027_discord_webhook_identifier_mt5_webhook_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5_webhook',
            name='status',
            field=models.CharField(default='active', max_length=10),
            preserve_default=False,
        ),
    ]
