# Generated by Django 4.2.2 on 2024-03-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signal_api', '0029_closeorder_discord_webhook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binance_Webhook',
        ),
        migrations.RenameField(
            model_name='discord_webhook',
            old_name='id',
            new_name='webhook_id',
        ),
        migrations.RemoveField(
            model_name='closeorder',
            name='discord_webhook',
        ),
        migrations.RemoveField(
            model_name='closeorder',
            name='mt5_webhook',
        ),
        migrations.RemoveField(
            model_name='closeorder',
            name='telegram_webhook',
        ),
        migrations.RemoveField(
            model_name='modifyorder',
            name='discord_webhook',
        ),
        migrations.RemoveField(
            model_name='modifyorder',
            name='mt5_webhook',
        ),
        migrations.RemoveField(
            model_name='modifyorder',
            name='telegram_webhook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discord_webhook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mt5_webhook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='telegram_webhook',
        ),
        migrations.AddField(
            model_name='closeorder',
            name='literal_webhook_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modifyorder',
            name='literal_webhook_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modifyorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='literal_webhook_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
