# Generated by Django 4.2.2 on 2024-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0031_discord_webhook_status_alter_mt5_webhook_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_webhook',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='subscription_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discord_webhook',
            name='identifier',
            field=models.CharField(default='discord', max_length=10),
        ),
        migrations.AlterField(
            model_name='telegram_webhook',
            name='identifier',
            field=models.CharField(default='telegram', max_length=10),
        ),
    ]
