# Generated by Django 4.2.2 on 2024-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0032_telegram_webhook_ends_at_telegram_webhook_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_webhook',
            name='identifier',
            field=models.CharField(default='tg', max_length=10),
        ),
    ]
