# Generated by Django 4.2.2 on 2024-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0033_alter_telegram_webhook_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5_webhook',
            name='pause',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
