# Generated by Django 4.2.2 on 2024-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0034_mt5_webhook_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_webhook',
            name='chat_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegram_webhook',
            name='chat_limit',
            field=models.IntegerField(default=0),
        ),
    ]
