# Generated by Django 4.2.2 on 2024-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0036_order_alert_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='webhook_name',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
