# Generated by Django 4.2.2 on 2024-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0037_order_webhook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='webhook_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
