# Generated by Django 4.2.2 on 2024-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_api', '0038_alter_order_webhook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_webhook',
            name='pause',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='telegram_webhook',
            name='pause',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
