"""
Django settings for stilletto project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d6((rkfr7ov@tq02-(ctbb^%26qm!ipm7vf7=wh3=nnjtz9ms*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["deidara6026.pythonanywhere.com", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'signal_api',
    'rest_framework',
    'app',
]

AUTH_USER_MODEL = "accounts.CustomUser" 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stilletto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stilletto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


TELEGRAM = {
    'token': "6894838515:AAGDNmExrl-jVHjWslKWlhSZSblIt05egKo"
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers":{
        'lemon': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'lemon.log',
            'when': 'D', # daily, you can use 'midnight' as well
            'backupCount': 100, # 100 days backup
            'formatter': 'verbose',
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "general.log",
            "formatter":"verbose"
        },
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} {name} {levelname} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    'loggers': {
        'lemon': {
            'handlers': ['lemon', ], 
            'level': 'INFO',
            'propagate': False,
        },
        'signal_api': {
            'handlers': ['file', ], 
            'level': 'WARNING',
            'propagate': False,
        },
    },

}

LEMONSQUEEZY = {
    "api_key" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiJjNTk5ZTA4YmFhNjk4YzdkYTkxZTQzMGIzOThjYTAwOWZjNmZiNDcwOTBlZGIzNzUwMzliZjBlMDM4NmUyMjVhNzU3MGVkMTYyOTdkNjE0MyIsImlhdCI6MTcwMTgxMjcxOS43ODYzNjEsIm5iZiI6MTcwMTgxMjcxOS43ODYzNjUsImV4cCI6MjAxNzQzMTkxOS43NTkxMTgsInN1YiI6IjE3MDQxODciLCJzY29wZXMiOltdfQ.JiXJEyZANZ1bRcAItMsUZBVkp5OeADJ7eQ6ssDrZaejS1EVQ3wxB1ggsCHvjt6838x6IJ5mWkg5jKC2t-zinpKFKzw7SybyjTvJ4i7RN7Kwt49E-L_8EMVhm2kRoBJ8MZ82OUPmjfNp8UKjhJqV3NrtDJn4zyOJW6veZRPZRFO4_QGtNFebv_Tl13Cz1_8f5qQxNhMNnpWnBSmTdfhOeHRiGI8zmnEwC-U4_Z_wJY0NVfFGO4AeDt3ZBsDcv_BK3VNk21oETvf434E0icnhf5Zvc5hbvfoo_kTDcAXovpZ7RPDwUgKQO931zCKbfBG8C0jpCBRCN8Mw-3sKpHo8tO8M2jW8vNjI39UAhVTXV6TlYvv-DeyLVLcbnSyjrYeW5lQTDEyB8lozcA43ajFZoC1znDghqN1DWgLM1aJFheDEEUq2hVDyQDXM2pd6ZhgdikbSe7Aj-t9o3g9wkuOjNbkeKvGD9u0jlPfkqdJV2_-_l28-o80vS2M0suI66h7uR"
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "sent_emails"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
